### ISSUE TITLE
Lägga till ny

### ISSUE THREAD

**Issue by js223kz** [lw222gu/1dv450-lw222gu-clientApplication#4]
Skrev bara in Östergatan 16 utan ort och den la sig på Kattsundsgatan i Malmö. Kanske ett fält till med ort och validering på dessa fält.

Får inga felmeddelande när uppgifter i formuläret saknas eller är fel inskrivna. Vore bra med validering av alla fält.

Står inte hur man ska ange adress, lön eller titel. Placeholdertext vore nog bra.

**Comment by lw222gu** [comment]
Felmeddelanden fixade.
