### ISSUE TITLE
Radera post, taggar finns kvar

### ISSUE THREAD

**Issue by js223kz** [lw222gu/1dv450-lw222gu-clientApplication#8]
När jag raderar en post ligger taggarna kvar på första sidan. Vore kanske bra om taggarna raderades om de inte längre finns med i någon post.

**Comment by lw222gu** [comment]
Kommer inte radera taggarna då man inte kan veta hur andra tjänster använder taggarna (oooom det nu skulle finnas några andra tjänster :-) ). Däremot har jag gjort så nu att om en tagg inte har någon lön kopplad till sig så kommer den inte visas i listan i den här applikationen.
